// fixtures/react-label/src/App.tsx
import { useState, type FormEvent } from "react";

export function App() {
  const [displayName, setDisplayName] = useState("");
  const [status, setStatus] = useState("");

  function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const name = displayName.trim();
    setStatus(name ? `Profile saved for ${name}.` : "Enter a display name.");
  }

  return (
    <main>
      <h1>Account</h1>
      <form onSubmit={handleSubmit}>
        <input
          id="display-name"
          name="displayName"
          value={displayName}
          onChange={(event) => setDisplayName(event.target.value)}
          autoComplete="name"
        />
        <button type="submit">Save</button>
      </form>
      <p role="status" aria-live="polite">{status}</p>
    </main>
  );
}

// fixtures/vue-label/src/App.vue
<script setup>
import { ref } from "vue";

const displayName = ref("");
const status = ref("");

function handleSubmit() {
  const name = displayName.value.trim();
  status.value = name ? `Profile saved for ${name}.` : "Enter a display name.";
}
</script>

<template>
  <main>
    <h1>Account</h1>
    <form @submit.prevent="handleSubmit">
      <input
        id="display-name"
        v-model="displayName"
        name="displayName"
        autocomplete="name"
      >
      <button type="submit">Save</button>
    </form>
    <p role="status" aria-live="polite">{{ status }}</p>
  </main>
</template>
